### ISSUE TITLE
MinIO console docker image unavailable

### ISSUE THREAD

**Issue by AkshayGuptaK** [render-examples/minio#12]
The MinIO console docker images have all been removed from DockerHub by the MinIO team, citing deprecation of standalone console deployment as of version 0.31.0

Could this repository be revised to suggest the best way of setting up MinIO (+Console) on Render as a single web service?

**Comment by lexpierce** [comment]
Unfortunately, a web service can only expose a single port publicly. This will be updated with a solution soon that includes console access.

**Comment by lexpierce** [comment]
The repo has been updated to deploy a nginx reverse proxy to access the embedded console.
